//Types for Sign up objects
export const SIGNUP_OBJ_SUCCESS = "SIGNUP_OBJ_SUCCESS";
export const SIGNUP_OBJ_CLEAR = "SIGNUP_OBJ_CLEAR";

//Types for Signup
export const SIGNUP_REQUEST_REQUEST = "SIGNUP_REQUEST_REQUEST";
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const SIGNUP_REQUEST_FAILURE = "SIGNUP_REQUEST_FAILURE";

//Types for Login
export const LOGIN_REQUEST_REQUEST = "LOGIN_REQUEST_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";

//Types for Token
export const TOKEN_REQUEST_REQUEST = "TOKEN_REQUEST_REQUEST";
export const TOKEN_REQUEST_SUCCESS = "TOKEN_REQUEST_SUCCESS";
export const TOKEN_REQUEST_FAILURE = "TOKEN_REQUEST_FAILURE";

//Types for Interests
export const INTEREST_REQUEST_REQUEST = "INTEREST_REQUEST_REQUEST";
export const INTEREST_REQUEST_SUCCESS = "INTEREST_REQUEST_SUCCESS";
export const INTEREST_REQUEST_FAILURE = "INTEREST_REQUEST_FAILURE";

//Types for UnInterests
export const UNINTEREST_REQUEST_REQUEST = "UNINTEREST_REQUEST_REQUEST";
export const UNINTEREST_REQUEST_SUCCESS = "UNINTEREST_REQUEST_SUCCESS";
export const UNINTEREST_REQUEST_FAILURE = "UNINTEREST_REQUEST_FAILURE";

//Types for AddEvent
export const ADDEVENT_REQUEST_REQUEST = "ADDEVENT_REQUEST_REQUEST";
export const ADDEVENT_REQUEST_SUCCESS = "ADDEVENT_REQUEST_SUCCESS";
export const ADDEVENT_REQUEST_FAILURE = "ADDEVENT_REQUEST_FAILURE";

//Types for LikeEvent
export const LIKEEVENT_REQUEST_REQUEST = "LIKEEVENT_REQUEST_REQUEST";
export const LIKEEVENT_REQUEST_SUCCESS = "LIKEEVENT_REQUEST_SUCCESS";
export const LIKEEVENT_REQUEST_FAILURE = "LIKEEVENT_REQUEST_FAILURE";

//Types for UnLikeEvent
export const UNLIKEEVENT_REQUEST_REQUEST = "UNLIKEEVENT_REQUEST_REQUEST";
export const UNLIKEEVENT_REQUEST_SUCCESS = "UNLIKEEVENT_REQUEST_SUCCESS";
export const UNLIKEEVENT_REQUEST_FAILURE = "UNLIKEEVENT_REQUEST_FAILURE";

//Types for GETALLLIKEDEVENTS
export const GETALLLIKEDEVENTS_REQUEST_REQUEST =
  "GETALLLIKEDEVENTS_REQUEST_REQUEST";
export const GETALLLIKEDEVENTS_REQUEST_SUCCESS =
  "GETALLLIKEDEVENTS_REQUEST_SUCCESS";
export const GETALLLIKEDEVENTS_REQUEST_FAILURE =
  "GETALLLIKEDEVENTS_REQUEST_FAILURE";

//Types for GETALLPARTICIPATEDEVENTS
export const GETALLPARTICIPATEDEVENTS_REQUEST_REQUEST =
  "GETALLPARTICIPATEDEVENTS_REQUEST_REQUEST";
export const GETALLPARTICIPATEDEVENTS_REQUEST_SUCCESS =
  "GETALLPARTICIPATEDEVENTS_REQUEST_SUCCESS";
export const GETALLPARTICIPATEDEVENTS_REQUEST_FAILURE =
  "GETALLPARTICIPATEDEVENTS_REQUEST_FAILURE";

//Types for Participate Event
export const PARTICIPATEEVENT_REQUEST_REQUEST =
  "PARTICIPATEEVENT_REQUEST_REQUEST";
export const PARTICIPATEEVENT_REQUEST_SUCCESS =
  "PARTICIPATEEVENT_REQUEST_SUCCESS";
export const PARTICIPATEEVENT_REQUEST_FAILURE =
  "PARTICIPATEEVENT_REQUEST_FAILURE";

//Types for Un Participate Event
export const UNPARTICIPATEEVENT_REQUEST_REQUEST =
  "UNPARTICIPATEEVENT_REQUEST_REQUEST";
export const UNPARTICIPATEEVENT_REQUEST_SUCCESS =
  "UNPARTICIPATEEVENT_REQUEST_SUCCESS";
export const UNPARTICIPATEEVENT_REQUEST_FAILURE =
  "UNPARTICIPATEEVENT_REQUEST_FAILURE";

//Types for Get All events by interest
export const GETALLEVENTSBYINTEREST_REQUEST_REQUEST =
  "GETALLEVENTSBYINTEREST_REQUEST_REQUEST";
export const GETALLEVENTSBYINTEREST_REQUEST_SUCCESS =
  "GETALLEVENTSBYINTEREST_REQUEST_SUCCESS";
export const GETALLEVENTSBYINTEREST_REQUEST_FAILURE =
  "GETALLEVENTSBYINTEREST_REQUEST_FAILURE";

//Types for Get Followed Organizations
export const GETFOLLOWEDORGANIZATION_REQUEST_REQUEST =
  "GETFOLLOWEDORGANIZATION_REQUEST_REQUEST";
export const GETFOLLOWEDORGANIZATION_REQUEST_SUCCESS =
  "GETFOLLOWEDORGANIZATION_REQUEST_SUCCESS";
export const GETFOLLOWEDORGANIZATION_REQUEST_FAILURE =
  "GETFOLLOWEDORGANIZATION_REQUEST_FAILURE";

//Types for Get All Organizations
export const GETALLORGANIZATION_REQUEST_REQUEST =
  "GETALLORGANIZATION_REQUEST_REQUEST";
export const GETALLORGANIZATION_REQUEST_SUCCESS =
  "GETALLORGANIZATION_REQUEST_SUCCESS";
export const GETALLORGANIZATION_REQUEST_FAILURE =
  "GETALLORGANIZATION_REQUEST_FAILURE";

//Types for Follow Organizations
export const FOLLOWORGANIZATION_REQUEST_REQUEST =
  "FOLLOWORGANIZATION_REQUEST_REQUEST";
export const FOLLOWORGANIZATION_REQUEST_SUCCESS =
  "FOLLOWORGANIZATION_REQUEST_SUCCESS";
export const FOLLOWORGANIZATION_REQUEST_FAILURE =
  "FOLLOWORGANIZATION_REQUEST_FAILURE";

//Types for UNFollow Organizations
export const UNFOLLOWORGANIZATION_REQUEST_REQUEST =
  "UNFOLLOWORGANIZATION_REQUEST_REQUEST";
export const UNFOLLOWORGANIZATION_REQUEST_SUCCESS =
  "UNFOLLOWORGANIZATION_REQUEST_SUCCESS";
export const UNFOLLOWORGANIZATION_REQUEST_FAILURE =
  "UNFOLLOWORGANIZATION_REQUEST_FAILURE";

//Types for GETALLEVENTSBYFOLLOWEDORG Organizations
export const GETALLEVENTSBYFOLLOWEDORG_REQUEST_REQUEST =
  "GETALLEVENTSBYFOLLOWEDORG_REQUEST_REQUEST";
export const GETALLEVENTSBYFOLLOWEDORG_REQUEST_SUCCESS =
  "GETALLEVENTSBYFOLLOWEDORG_REQUEST_SUCCESS";
export const GETALLEVENTSBYFOLLOWEDORG_REQUEST_FAILURE =
  "GETALLEVENTSBYFOLLOWEDORG_REQUEST_FAILURE";

//Types for GETALLEVENTSBYSPECIFICORG Organizations
export const GETALLEVENTSBYSPECIFICORG_REQUEST_REQUEST =
  "GETALLEVENTSBYSPECIFICORG_REQUEST_REQUEST";
export const GETALLEVENTSBYSPECIFICORG_REQUEST_SUCCESS =
  "GETALLEVENTSBYSPECIFICORG_REQUEST_SUCCESS";
export const GETALLEVENTSBYSPECIFICORG_REQUEST_FAILURE =
  "GETALLEVENTSBYSPECIFICORG_REQUEST_FAILURE";
